// <auto-generated />
using System;
using GifFind.API.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GifFind.API.Migrations
{
    [DbContext(typeof(GifFindContext))]
    [Migration("20190819234953_Init_GifFind")]
    partial class Init_GifFind
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GifFind.API.Entities.Category", b =>
                {
                    b.Property<Guid>("CategoryID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CategoryName");

                    b.Property<Guid>("UserID");

                    b.HasKey("CategoryID");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("GifFind.API.Entities.SavedImage", b =>
                {
                    b.Property<Guid>("SavedImageID")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("CategoryID");

                    b.HasKey("SavedImageID");

                    b.ToTable("SavedImages");
                });
#pragma warning restore 612, 618
        }
    }
}
